
esphome:
  name: levoit-core300s-s3
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:  
  level: VERBOSE

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: "mista3"
  password: "vvfpnhk8vBfh"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Levoit-Vital100S"
    password: "1ZjzfekrSvRt"

captive_portal:

external_components:
  - source: ../../../components
    components: [levoit]

uart:
  - id: uart_mcu2esp
    tx_pin: 
      number: GPIO04
      inverted: false
    rx_pin: 
      number: GPIO05
      inverted: false
    baud_rate: 115200

levoit:
  id: levoitcore300
  model: CORE300S
fan:
  - platform: levoit
    levoit: levoitcore300
    name: "Fan"
    id: levoit_fan1  
switch:
  - platform: levoit
    levoit: levoitcore300
    name: "Display"
    type: display
  - platform: levoit
    levoit: levoitcore300
    name: "Child Lock"
    type: child_lock

number:
  - platform: levoit
    levoit: levoitcore300
    name: "Auto Mode Room Size"
    type: efficiency_room_size
  - platform: levoit
    levoit: levoitcore300
    name: "Timer (min)"
    type: timer
sensor:

  - platform: levoit
    levoit: levoitcore300
    name: "PM 2.5"
    type: pm25
  - platform: levoit
    levoit: levoitcore300
    name: "AQI"
    type: aqi
# Better: auto_mode_room_size_high_fan text_sensor    
#  - platform: levoit
#    levoit: levoitcore300
#    name: "Efficiency Count Dowmn Timer (sec)"
#    type: efficiency_counter
# Better: timer_duration_remaining text_sensor    
#  - platform: levoit
#    levoit: levoitcore300
#    name: "Timer Remaining"
#    type: timer_current
select:
  - platform: levoit
    levoit: levoitcore300
    name: "Auto Mode"
    type: auto_mode
text_sensor:
  - platform: levoit
    levoit: levoitcore300
    name: "MCU Version"
    type: mcu_version
  - platform: levoit
    levoit: levoitcore300
    name: "ESP Version"
    type: esp_version
  - platform: levoit
    levoit: levoitcore300
    name: "Timer Duration"
    type: timer_duration_initial
  - platform: levoit
    levoit: levoitcore300
    name: "Timer Remaining"
    type: timer_duration_remaining
  - platform: levoit
    levoit: levoitcore300
    name: "Error"
    type: error_message
#  Only for Vital100S and Vital200S
#  - platform: levoit
#    levoit: levoitcore300
#    name: "Auto: High remaining run time"
#    type: auto_mode_room_size_high_fan