#example levoit-vital200s.yaml for flashing the original ESP32-SOLO-1C
substitutions:
  device_name: levoit-vital200s
  wifi_ap_ssid: "Levoit-Vital200S"
  rx_pin: GPIO05
  tx_pin: GPIO06

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

<<: !include common.yaml
