#example levoit-vital200s.yaml for flashing the original ESP32-SOLO-1C
substitutions:
  device_name: levoit-vital200s
  wifi_ap_ssid: "Levoit-Vital200S"
  rx_pin: GPIO18                            
  tx_pin: GPIO19                     

esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1    
  framework:
    type: esp-idf

packages:
  common: !include common.yaml
  source: !include ../packages/source_git.yaml
