#example levoit-vital100s.yaml for flashing the original ESP32-SOLO-1C
substitutions:
  device_name: levoit-vital100s
  wifi_ap_ssid: "Levoit-Vital100S"
  rx_pin: GPIO05
  tx_pin: GPIO06

esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
#    sdkconfig_options:
#      CONFIG_FREERTOS_UNICORE: y

packages:
  common: !include common.yaml
  source: !include ../packages/source_local.yaml
