esphome:
  name: pm1003-test

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: "a4m3xb"

wifi:
  ssid: "mista3"
  password: "vvfpnhk8vBfh"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pm1003-Test Fallback Hotspot"
    password: "DaJFgBPUyDqk"

captive_portal:

uart:
  tx_pin: GPIO21
  rx_pin: GPIO22
  baud_rate: 9600
sensor:
  - platform: pm100x
    model: PM1003
    id: pm1003_sensor
    update_interval: 0s
    pm_2_5:
      name: "PM2.5"
#    pwm:
#      pin:
#        number: GPIO23
#        inverted: true