esphome:
  name: levoit-everest-air
  friendly_name: Levoit Everest Air
  name_add_mac_suffix: true
  min_version: 2026.5.3

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

external_components:
  - source:
      type: git
      url: https://github.com/tuct/levoit
      ref: 1.4.2
    components: [levoit]

wifi:
  # Set up a wifi access point using the device name above
  ap:

uart:
  - id: uart_mcu2esp
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 115200

levoit:
  id: purifier
  model: EVERESTAIR

fan:
  - platform: levoit
    levoit: purifier
    id: levoit_fan
    name: "Fan"

switch:
  - platform: levoit
    levoit: purifier
    id: levoit_display
    name: "Display"
    type: display
  - platform: levoit
    levoit: purifier
    id: levoit_child_lock
    name: "Child Lock"
    type: child_lock
  - platform: levoit
    levoit: purifier
    id: levoit_light_detect
    name: "Light Detect"
    type: light_detect

select:
  - platform: levoit
    levoit: purifier
    id: levoit_auto_mode
    name: "Auto Mode"
    type: auto_mode

sensor:
  - platform: levoit
    levoit: purifier
    id: levoit_pm1
    name: "AQ - PM 1.0"
    type: pm1_0
  - platform: levoit
    levoit: purifier
    id: levoit_pm25
    name: "AQ - PM 2.5"
    type: pm25
  - platform: levoit
    levoit: purifier
    id: levoit_pm10
    name: "AQ - PM 10"
    type: pm10
  - platform: levoit
    levoit: purifier
    id: levoit_aqi
    name: "AQI"
    type: aqi
  - platform: levoit
    levoit: purifier
    id: levoit_cadr
    name: "Current CADR"
    type: current_cadr
  - platform: levoit
    levoit: purifier
    id: levoit_filter_life
    name: "Filter %"
    type: filter_life_left

binary_sensor:
  - platform: levoit
    levoit: purifier
    id: levoit_filter_low
    name: "Filter Low"
    type: filter_low
  - platform: levoit
    levoit: purifier
    id: levoit_cover_open
    name: "Cover Open"
    type: cover_open

number:
  - platform: levoit
    levoit: purifier
    id: levoit_timer
    name: "Timer (min)"
    type: timer
  - platform: levoit
    levoit: purifier
    id: levoit_filter_lifetime
    name: "Filter Months"
    type: filter_lifetime_months
  - platform: levoit
    levoit: purifier
    id: levoit_vent_angle
    name: "Vent Angle"
    type: vent_angle

button:
  - platform: levoit
    levoit: purifier
    id: levoit_reset_filter
    name: "Filter Reset"
    type: reset_filter_stats

text_sensor:
  - platform: levoit
    levoit: purifier
    id: levoit_mcu_version
    name: "MCU Version"
    type: mcu_version
