substitutions:
  name: "levoit-core400s"

esphome:
  name: ${name}
  project: 
    name: "Levoit.Core400s"
    version: "1.0.0"
 
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

# Enable logging
logger:  
  level: VERBOSE

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: "mista3"
  password: "vvfpnhk8vBfh"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Levoit-Vital100S"
    password: "1ZjzfekrSvRt"

captive_portal:

#external_components:
#  - source: ../../../components
#    components: [levoit]

external_components:
  - source:
      type: git
      url: https://github.com/tuct/esphome-projects
      ref: main
    components: [levoit]

uart:
  - id: uart_mcu2esp
    tx_pin: 
      number: GPIO17
      inverted: false
    rx_pin: 
      number: GPIO16
      inverted: false
    baud_rate: 115200

levoit:
  id: levoitcore400
  model: CORE400S
fan:
  - platform: levoit
    levoit: levoitcore400
    name: "Fan"
    id: levoit_fan1  
switch:
  - platform: levoit
    levoit: levoitcore400
    name: "Display"
    type: display
  - platform: levoit
    levoit: levoitcore400
    name: "Child Lock"
    type: child_lock

number:
  - platform: levoit
    levoit: levoitcore400
    name: "Auto Mode Room Size"
    type: efficiency_room_size
  - platform: levoit
    levoit: levoitcore400
    name: "Timer (min)"
    type: timer
  - platform: levoit
    levoit: levoitcore400
    name: "Filter Months"
    type: filter_lifetime_months
sensor:

  - platform: levoit
    levoit: levoitcore400
    name: "AQ - PM 2.5"
    type: pm25
  - platform: levoit
    levoit: levoitcore400
    name: "AQI"
    type: aqi
  - platform: levoit
    levoit: levoitcore400
    name: "Current CADR"
    type: current_cadr
  - platform: levoit
    levoit: levoitcore400
    name: "Filter %"
    type: filter_life_left
# Better: auto_mode_room_size_high_fan text_sensor    
#  - platform: levoit
#    levoit: levoitcore400
#    name: "Efficiency Count Dowmn Timer (sec)"
#    type: efficiency_counter
# Better: timer_duration_remaining text_sensor    
#  - platform: levoit
#    levoit: levoitcore400
#    name: "Timer Remaining"
#    type: timer_current
select:
  - platform: levoit
    levoit: levoitcore400
    name: "Auto Mode"
    type: auto_mode
text_sensor:
  - platform: levoit
    levoit: levoitcore400
    name: "MCU Version"
    type: mcu_version
  - platform: levoit
    levoit: levoitcore400
    name: "ESP Version"
    type: esp_version
  - platform: levoit
    levoit: levoitcore400
    name: "Timer Duration"
    type: timer_duration_initial
  - platform: levoit
    levoit: levoitcore400
    name: "Timer Remaining"
    type: timer_duration_remaining
  - platform: levoit
    levoit: levoitcore400
    name: "Error"
    type: error_message
button:
  - platform: levoit
    levoit: levoitcore400
    name: "Filter Reset"
    type: reset_filter_stats
binary_sensor:
  - platform: levoit
    levoit: levoitcore400
    name: "Filter Low"
    type: filter_low
#  Only for Vital100S and Vital200S
#  - platform: levoit
#    levoit: levoitcore400
#    name: "Auto: High remaining run time"
#    type: auto_mode_room_size_high_fan