#example levoit-core400s-s3.yaml for flashing a new ESP32-S3
substitutions:
  device_name: levoit-core400s-s3
  wifi_ap_ssid: "Levoit-Core400S"
  rx_pin: GPIO05
  tx_pin: GPIO04

esphome:
  name: ${device_name}
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

<<: !include common.yaml
