#Do not use this file directly, it is included in the device yaml files. Put common configuration here.
esphome:
  name: ${device_name}

# Enable logging
logger:
  level: VERBOSE

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "${wifi_ap_ssid}"
    password: !secret wifi_ap_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/tuct/levoit
      ref: main
    components: [levoit]

uart:
  - id: uart_mcu2esp
    tx_pin:
      number: ${tx_pin}
      inverted: false
    rx_pin:
      number: ${rx_pin}
      inverted: false
    baud_rate: 115200

levoit:
  id: levoitsprout
  model: SPROUT

fan:
  - platform: levoit
    levoit: levoitsprout
    name: "Fan"
    id: levoit_fan1

switch:
  - platform: levoit
    levoit: levoitsprout
    name: "Display"
    type: display
  - platform: levoit
    levoit: levoitsprout
    name: "Child Lock"
    type: child_lock
  - platform: levoit
    levoit: levoitsprout
    name: "Light Detect"
    type: light_detect
  - platform: levoit
    levoit: levoitsprout
    name: "White Noise"
    type: white_noise

number:
  - platform: levoit
    levoit: levoitsprout
    name: "Timer (min)"
    type: timer
  - platform: levoit
    levoit: levoitsprout
    name: "Auto Mode Room Size"
    type: efficiency_room_size
  - platform: levoit
    levoit: levoitsprout
    name: "Filter Months"
    type: filter_lifetime_months
  # Breathing effect params
  - platform: levoit
    levoit: levoitsprout
    name: "LED Brightness Min"
    type: led_brightness_min
  - platform: levoit
    levoit: levoitsprout
    name: "LED Breathing Time (s)"
    type: led_speed
  - platform: levoit
    levoit: levoitsprout
    name: "AQI Scale"
    type: aqi_scale
  # White noise
  - platform: levoit
    levoit: levoitsprout
    name: "White Noise Volume"
    type: white_noise_volume

sensor:
  - platform: levoit
    levoit: levoitsprout
    name: "PM 2.5"
    type: pm25
    id: sprout_pm25
  - platform: levoit
    levoit: levoitsprout
    name: "PM 1.0"
    type: pm1_0
  - platform: levoit
    levoit: levoitsprout
    name: "PM 10"
    type: pm10
    id: sprout_pm10
  - platform: aqi
    name: "AQI"
    pm_2_5: sprout_pm25
    pm_10_0: sprout_pm10
    calculation_type: AQI
  - platform: levoit
    levoit: levoitsprout
    name: "Fan RPM"
    type: fan_rpm
  - platform: levoit
    levoit: levoitsprout
    name: "Current CADR"
    type: current_cadr
  - platform: levoit
    levoit: levoitsprout
    name: "Filter %"
    type: filter_life_left

light:
  - platform: levoit
    levoit: levoitsprout
    name: "LED Ring"
    gamma_correct: 0
    default_transition_length: 0s

select:
  - platform: levoit
    levoit: levoitsprout
    name: "Auto Mode"
    type: auto_mode
  - platform: levoit
    levoit: levoitsprout
    name: "White Noise Sound"
    type: white_noise_sound

text_sensor:
  - platform: levoit
    levoit: levoitsprout
    name: "MCU Version"
    type: mcu_version
  - platform: levoit
    levoit: levoitsprout
    name: "ESP Version"
    type: esp_version
  - platform: levoit
    levoit: levoitsprout
    name: "Timer Duration"
    type: timer_duration_initial
  - platform: levoit
    levoit: levoitsprout
    name: "Timer Remaining"
    type: timer_duration_remaining
  - platform: levoit
    levoit: levoitsprout
    name: "Auto: High remaining run time"
    type: auto_mode_room_size_high_fan
  - platform: levoit
    levoit: levoitsprout
    name: "Error"
    type: error_message
  - platform: levoit
    levoit: levoitsprout
    name: "Last MCU Event"
    type: sprout_event

button:
  - platform: levoit
    levoit: levoitsprout
    name: "Filter Reset"
    type: reset_filter_stats

binary_sensor:
  - platform: levoit
    levoit: levoitsprout
    name: "Filter Low"
    type: filter_low
  - platform: levoit
    levoit: levoitsprout
    name: "Cover Open"
    type: cover_open
