esphome:
  name: mista-door-indicator
  #needed to reset the servo, stupid bug
  on_boot:
    priority: 100
    then:
      - servo.detach: lid_servo
      - servo.write:
          id: lid_servo
          level: !lambda |-
            auto np = (double)(id(last_servo_pos)/100);
            return np; //id(last_servo_pos)/100;

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


globals:
  - id: last_servo_pos
    type: int
    restore_value: yes
    initial_value: '0'
script:
  - id: open_iris
    then:
      - logger.log: "Open start"
      - servo.write:
          id: lid_servo
          level: 100.0% 
      - globals.set:
          id: last_servo_pos
          value: '100'

      - logger.log: "Open done"
      - delay: 1s
      - light.turn_on:
          id: door_indicator_light
          brightness: 1.0
          red: 100%
          green: 0%
          blue: 0%
          effect: "Slow Pulse"
  - id: close_iris
    then:
      - light.turn_off:
          id: door_indicator_light
      - logger.log: "Close start"
      - servo.write:
          id: lid_servo
          level: -100.0% 
      - globals.set:
          id: last_servo_pos
          value: '-100'
      - logger.log: "Close done"
    
  - id: toggle_iris
    then:
      - if:
          condition:
            lambda: 'return id(last_servo_pos) <= 0;'
          then:
            - script.execute: open_iris
          else:
            - script.execute: close_iris

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    id: button_a
    on_release:
      then:
        - script.execute: toggle_iris
switch:
  - platform: template
    name: "Iris Lid Open"
    lambda: |-
      if (id(last_servo_pos)==100) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - script.execute: open_iris
    turn_off_action:
      - script.execute: close_iris
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO16
    num_leds: 1
    chipset: ws2812
    name: "Door Indicator Light"
    id: door_indicator_light
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s
          update_interval: 1s
output:
  - platform: ledc
    id: pwm_servo
    pin: GPIO14
    channel: 6
    frequency: 50Hz   
servo:
  - id: lid_servo
    output: pwm_servo
    transition_length: 1s
    auto_detach_time: 500ms
    restore: no
    min_level: 0.5%
    idle_level: 7.5%
    max_level: 20%
    